### ISSUE TITLE
Documenation is unclear => unable to build 😞

### ISSUE THREAD

**Issue by AnharMiah** [wasm3/wasm3-openwrt-packages#1]
Hello Wasm3 team!

Thanks for creating this excellent project, I highly appreciate the hard work that goes into open source software.

WASM3 got my attention because it can target both `ESP8266` as well as `OpenWRT` so of course I was super excited to try it!

I've started with OpenWRT but so far I've failed to build :cry: 

the documentation is very unclear, this is the only information I have to go by:

```shell
echo "src-git wasm3 git://github.com/wasm3/wasm3-openwrt-packages.git" >> ./feeds.conf
./scripts/feeds update -a
./scripts/feeds install -p wasm3 -a
make menuconfig
```

# Steps to reproduce:

* spin up new clean VM ubuntu 18.04 _(e.g using vagrant up)_
* `sudo apt-get install make` _(docs does not mention what is required, but we assume this because there is a Makefile)_
* in the new machine clone down this repo and cd into it:

```shell
$ git clone https://github.com/wasm3/wasm3-openwrt-packages/
$ cd wasm3-openwrt-packages/
```

now follow the first step in "documentation":

```shelll
$ echo "src-git wasm3 git://github.com/wasm3/wasm3-openwrt-packages.git" >> ./feeds.conf
```

ok so far so good, next follow next line:

```shell
$ ./scripts/feeds update -a
-bash: ./scripts/feeds: No such file or directory
```

ok, clearly that directory doesn't exist!

I'm really sorry if this is perhaps very simple! but clear build steps and exactly what dependencies are required would be super appreciated!

**Comment by AnharMiah** [comment]
**update 1**

so reading the official wiki on OpenWRT lead to the following page:

https://openwrt.org/docs/guide-developer/build.a.package

So now I'm trying again

**Comment by vshymanskyy** [comment]
@AnharMiah did you succeed?

**Comment by AnharMiah** [comment]
hi @vshymanskyy to be honest I've totally forgotten about this! thanks for the bump, if I get some time in the weekend I might give it another crack. I think I just need to follow the OpenWRT build instructions.

**Comment by vshymanskyy** [comment]
That is correct, let me update the documentation to reflect this. Sorry for confusion!
