### ISSUE TITLE
I need your help.

### ISSUE THREAD

**Issue by darkhorse0322** [wasm3/wasm3-openwrt-packages#2]
Hi @vshymanskyy 
Hope you are well.
Thank you for your wonderful project and for sharing it with us.

So I am going to use this package in the Openwrt based device and build a Python package.
I could build the executable package according to your document, it was correct.

But, I need to build it as a Python package so that I could use it with Python on my device.
So how can I do that? So should I edit the make file?
Could you please let me know about this solution?

Thank you so much.

**Comment by vshymanskyy** [comment]
This package is only for native `wasm3` executable. If you'd like to run `pywasm3`, you need to use this:
https://github.com/wasm3/pywasm3
However you'll have to learn how to include it in your openwrt build. It would be cool if you could share your experience in that direction.

**Comment by darkhorse0322** [comment]
Hi 
Thank you for your kind update.
Okay, I will have a look.
Regards.
