### ISSUE TITLE
Error: WASI not linked when executing on openwrt

### ISSUE THREAD

**Issue by tsingyawn** [wasm3/wasm3-openwrt-packages#3]
- Hi, @vshymanskyy Thank you for your awesome project. I hope you can help me solve the problem of using wasm on openwrt.

- When I followed the steps to generate the .ipk file, the following warning appeared, but the wasm3_0.5.0-1_x86_64.ipk file was generated normally. （OS: centOS7）

  ```
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'eip197-mini-firmware', which does not exist
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'r8169-firmware', which does not exist
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'e100-firmware', which does not exist
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'bnx2-firmware', which does not exist
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'bnx2x-firmware', which does not exist
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'ar3k-firmware', which does not exist
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'mwifiex-sdio-firmware', which does not exist
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb2', which does not exist
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'edgeport-firmware', which does not exist
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb3', which does not exist
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'amdgpu-firmware', which does not exist
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'radeon-firmware', which does not exist
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'prism54-firmware', which does not exist
  WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'rtl8192su-firmware', which does not exist
  tmp/.config-package.in:72:warning: ignoring type redefinition of 'PACKAGE_libc' from 'bool' to 'tristate'
  tmp/.config-package.in:100:warning: ignoring type redefinition of 'PACKAGE_libgcc' from 'bool' to 'tristate'
  tmp/.config-package.in:221:warning: ignoring type redefinition of 'PACKAGE_libpthread' from 'bool' to 'tristate'
  tmp/.config-package.in:249:warning: ignoring type redefinition of 'PACKAGE_librt' from 'bool' to 'tristate'
  ```

- Then, I successfully installed the .ipk file on the openwrt system.

- I want to verify whether openwrt can use wasm3 normally. So I followed the instructions at https://github.com/wasm3/wasm3/blob/main/docs/Cookbook.md and created the hello.wasm file on centOS following the instructions in the Rust WASI app section.

- When I copied hello.wasm to the openwrt system, I found the following error.

  ```
  root@OpenWrt:~# wasm3 hello.wasm 
  Error: WASI not linked
  ```

- Could you help me analyze what went wrong? In addition, I noticed that this issue https://github.com/wasm3/wasm3-openwrt-packages/issues/2 mentioned "This package is only for native wasm3 executable.". Can you provide a demo of wasm file that can run on openwrt?

**Comment by tsingyawn** [comment]
An openwrt-like version of the book that has been provided. This SDK version is openwrt-sdk-21.02.1-x86-64_gcc-8.4.0_musl.Linux-x86_64, and the systematic version is openwrt-21.02.1-x86-64-generic-ext4-combined-efi.

**Comment by tsingyawn** [comment]
This SDK version is openwrt-sdk-21.02.1-x86-64_gcc-8.4.0_musl.Linux-x86_64, and the systematic version is openwrt-21.02.1-x86-64-generic-ext4-combined-efi. Thanks a lot.

**Comment by vshymanskyy** [comment]
Do you absolutely need to build the openwrt package for WASI usage?
You should be able to use the statically-linked binaries, provided by Wasm3 release:
- For x86_64: https://github.com/wasm3/wasm3/releases/download/v0.5.0/wasm3-linux-x64.elf
- For other architectures: https://github.com/wasm3/wasm3/releases/download/v0.5.0/wasm3-linux-other.tar.gz

These were tested on OpenWrt. I.e. you should be able to run CoreMark 1.0 WASI build:
https://github.com/wasm3/wasm3/blob/main/test/wasi/coremark/coremark.wasm

**Comment by vshymanskyy** [comment]
The `WARNING: Makefile ...` messages seem to be unrelated to Wasm3

**Comment by tsingyawn** [comment]
Thank you for your answer! I am able to use the statically-linked binaries. The wasm file can be executed normally.

I hope to be able to use the openwrt SDK to build the ipk file through https://github.com/wasm3/wasm3-openwrt-packages/blob/main/wasm3/wasm3/Makefile and make the wasm file execute normally. May I ask How should it be done?

Sorry, I am actually a beginner in openwrt and WASM3. Thanks again for your help.

**Comment by vshymanskyy** [comment]
@tsingyawn I have added a simple wasi implementation, but it required changes in Wasm3 main repository.
I had to switch `wasm3-openwrt-packages ` to use the main branch, so you need to update feeds and verify that main branch is downloaded instead of 0.5.0 release

**Comment by vshymanskyy** [comment]
Also added static prebuilt binaries to this repository:
https://github.com/wasm3/wasm3-openwrt-packages/blob/main/README.md#using-static-prebuilt-binaries

Static binaries use libuv + uvwasi under the hood, so it's [better and more complete](https://github.com/wasm3/wasm3/blob/main/source/m3_api_uvwasi.c).
`wasm3-openwrt-packages` package currently uses a [direct, incomplete WASI implementation](https://github.com/wasm3/wasm3/blob/main/source/m3_api_wasi.c).
